
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            Sweden/Stockholm # eg. Asia/Kathmandu
locale:              en_uk # eg. en_us
name:				         Stiff Women
title:               Female representation in the public space
tagline:             'tagline'
description:         'description'
url:                 site url
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'

author:
  name:           	 Ellen Kendall
  url:            	 stiffwomen.github.io

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "haml"]
port:             	 9001

sass:
  sass_dir: _sass

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
